# Generated by Django 6.0.7 on 2026-08-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ratings',
            new_name='rating',
        ),
    ]
